In [1]:
import numpy as np
a=np.array(4)
print(a)

4


In [3]:
a.ndim


0

In [5]:
b=np.array([1,2,3,4])

In [6]:
print(b)

[1 2 3 4]


In [7]:
b.ndim

1

In [8]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
mat.ndim

2